### PR TITLE
feat: add userbradley as code owner

### PR DESCRIPTION
**Pull request by CyberHippo**
Updating the `CODEOWNERS` file to include `Bradley Jenkins` AKA @userbradley

### CODE REVIEW

**Comment by userbradley** [comment]
he @CyberHippo  can you send the repo invitation again... I never saw it until it expired just how haha!

**Comment by CyberHippo** [comment]
Hi @userbradley , no worries 
I just sent you another one

**Comment by userbradley** [comment]
Thanks! I've tried to update this PR but I dont have push permissions!

image


image

**Comment by CyberHippo** [comment]
My bad, should be fine now @userbradley

**Comment by userbradley** [comment]
PR seems to be ready to merge, I can confirm the `CODEOWNERS` file is valid 

image

**Review by userbradley — APPROVED** [review]

**Comment by CyberHippo** [comment]
Thanks @userbradley. I'll wait for another member of the team to approve it on Monday

**Review by Quche — APPROVED** [review]
ok

**Pull request merged**
